[package]
name    = "ui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos                       = { workspace = true, features = ["csr","ssr"] }
leptos_router                = { workspace = true }
leptos_meta                  = { workspace = true }
wgpu                         = { workspace = true }
wasm-bindgen                 = { workspace = true }
console_error_panic_hook     = { workspace = true }
pollster                     = { workspace = true }
