name: Deploy to Fly.io
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: latest

      - name: Set secrets without staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          PROJECTS_PAT: ${{ secrets.PROJECTS_PAT }}
        run: flyctl secrets set PROJECTS_PAT="$PROJECTS_PAT" -a yus

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only -a yus

