name: Deploy to Fly.io
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@v1

    - name: Update PAT if changed
      run: flyctl secrets set --stage PROJECTS_PAT="${{ secrets.PROJECTS_PAT }}" -a yus

    - name: Deploy
      run: flyctl deploy -a yus
